In [2]:
import numpy as np

## Sum

In [3]:
m1 = np.array([[1,2,3],[2,3,4],[4,5,6]])
# 1,2,3
# 2,3,4
# 4,5,6

print(f"m1 shape {m1.shape}")
print(f"axis 2{m1[2]}")

m = np.sum(m1, axis=0)
m

m1 shape (3, 3)
axis 2[4 5 6]


array([ 7, 10, 13])

## Equality

In [4]:
m1 = np.array([1,2,3,4])
m2 = np.array([2,2,3,4])

m3 = np.equal(m1, m2)
m3

array([False,  True,  True,  True])

In [5]:
m3 = np.equal(m1, 1)
m3

array([ True, False, False, False])

In [6]:
m4 = (m1 == m3)
m4

array([ True, False, False, False])

## Dot Product

In [7]:
m1 = np.array([1,2,3,4])
m2 = np.array([1,2,3,4])
m3 = np.dot(m1, m2)
m3

30

In [8]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[1,2],[3,4],[5,6]])
m3 = np.dot(m1, m2)
m3

array([[22, 28],
       [49, 64]])