# Linear Algebra with Numpy

In [1]:
import numpy as np

## Defining lists and numpy arrays

In [5]:
py_list = [1,2,3,4,5]
np_array = np.array(py_list)
np_array

array([1, 2, 3, 4, 5])

In [6]:
print(py_list)
print(np_array)
print(type(py_list))
print(type(np_array))


[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>


## Algebraic operators on Numpy arrays vs Python Lists

In [7]:
print(np_array + np_array)
print(py_list + py_list)

[ 2  4  6  8 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [8]:
print(np_array * 3)
print(py_list * 3)

[ 3  6  9 12 15]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


## Matrix Operations

In [9]:
npmatrix1 = np.array([np_array, np_array, np_array])
npmatrix2 = np.array([py_list, [1,2,3,4,5], np.ones(5)])

print(npmatrix1)
print(npmatrix2)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 1. 1. 1. 1.]]


## Scaling and translating matrices

In [11]:
new_matrix = np.array([[1,2],[3,4]])
print(new_matrix)

[[1 2]
 [3 4]]


In [14]:
print(new_matrix * 2 + 1)
print(new_matrix + new_matrix)
print(new_matrix - new_matrix)

[[3 5]
 [7 9]]
[[2 4]
 [6 8]]
[[0 0]
 [0 0]]


## Transpose Matrix

In [17]:
matrix_3x2 = np.array([[1,2],[3,4],[5,6]])
print("Original 3 x 2 matrix")
print(matrix_3x2)
print("Transposed 3 x 2 matrix")
print(matrix_3x2.T)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
