# Linear Algebra with Numpy

In [1]:
import numpy as np

## Defining lists and numpy arrays

In [2]:
py_list = [1,2,3,4,5]
np_array = np.array(py_list)
np_array

array([1, 2, 3, 4, 5])

In [3]:
print(py_list)
print(np_array)
print(type(py_list))
print(type(np_array))


[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>


## Algebraic operators on Numpy arrays vs Python Lists

In [4]:
print(np_array + np_array)
print(py_list + py_list)

[ 2  4  6  8 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [5]:
print(np_array * 3)
print(py_list * 3)

[ 3  6  9 12 15]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


## Matrix Operations

In [6]:
npmatrix1 = np.array([np_array, np_array, np_array])
npmatrix2 = np.array([py_list, [1,2,3,4,5], np.ones(5)])

print(npmatrix1)
print(npmatrix2)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 1. 1. 1. 1.]]


## Scaling and translating matrices

In [7]:
new_matrix = np.array([[1,2],[3,4]])
print(new_matrix)

[[1 2]
 [3 4]]


In [8]:
print(new_matrix * 2 + 1)
print(new_matrix + new_matrix)
print(new_matrix - new_matrix)

[[3 5]
 [7 9]]
[[2 4]
 [6 8]]
[[0 0]
 [0 0]]


## Transpose Matrix

In [9]:
matrix_3x2 = np.array([[1,2],[3,4],[5,6]])
print("Original 3 x 2 matrix")
print(matrix_3x2)
print("Transposed 3 x 2 matrix")
print(matrix_3x2.T)

Original 3 x 2 matrix
[[1 2]
 [3 4]
 [5 6]]
Transposed 3 x 2 matrix
[[1 3 5]
 [2 4 6]]


## Dot Product

In [16]:
n_array1 = np.array([[1,1,3],[2,4,2],[3,6,2]])
n_array2 = np.array([[5,2,1],[3,0,1],[2,1,1]])

dot_product = np.dot(n_array1, n_array2)
print(f"First dot product {dot_product}")

n_array3 = np.array([[1,1,3],[2,4,2],[3,6,2]])
n_array4 = np.array([[5,2],[3,0],[2,1]])

dot_product2 = np.dot(n_array3, n_array4)
print(f"Second dot product {dot_product2}")

nparray1 = np.array([0, 1, 2, 3]) # Define an array
nparray2 = np.array([4, 5, 6, 7]) # Define an array

flavor1 = np.dot(nparray1, nparray2) # Recommended way
print(flavor1)

flavor2 = np.sum(nparray1 * nparray2) # Ok way
print(flavor2)

flavor3 = nparray1 @ nparray2         # Geeks way
print(flavor3)

# As you never should do:             # Noobs way
flavor4 = 0
for a, b in zip(nparray1, nparray2):
    flavor4 += a * b
    
print(flavor4)

First dot product [[14  5  5]
 [26  6  8]
 [37  8 11]]
Second dot product [[14  5]
 [26  6]
 [37  8]]
38
38
38
38


## Vector Norm

In [18]:
arr1 = np.array([1,2,3])
print(np.linalg.norm(arr1))

3.7416573867739413


## Center columns of a matrix

In [17]:
np_array1 = np.array([[1,3],[2,4]])
centered_by_column = np_array1 - np.mean(np_array1, axis=0)
centered_by_row = np_array1 - np.mean(np_array1, axis=1)
print(f"Centered by column {centered_by_column}")
print(f"Centered by row {centered_by_row}")

Centered by column [[-0.5 -0.5]
 [ 0.5  0.5]]
Centered by row [[-1.  0.]
 [ 0.  1.]]


## Cosine Similarity

cos(b) = (v * w) / (||v|| ||w||)

In [20]:
agriculture_corpus = np.array([20, 40])
history_corpus = np.array([30,20])

cosine_similarity = np.dot(agriculture_corpus, history_corpus) / (np.linalg.norm(agriculture_corpus) * np.linalg.norm(history_corpus))
print(cosine_similarity)

0.8682431421244591
