In [1]:
import numpy as np

## Joining (concatenation)

In [7]:
w_hh = np.full((3,2), 1)
w_hx = np.full((3,3), 9)

print("-- Data --\n")
print("w_hh :")
print(w_hh)
print("w_hh shape :", w_hh.shape, "\n")
print("w_hx :")
print(w_hx)
print("w_hx shape :", w_hx.shape, "\n")

# Joining the arrays
print(f"joining")
ww_h1 = np.concatenate((w_hh, w_hx), axis=1)
ww_h1
print(f"ww_h1 shape {ww_h1.shape}")

# Option 2: hstack
print("hstack")
w_h2 = np.hstack((w_hh, w_hx))
print(f"w_h2 shape {w_h2.shape}")

-- Data --

w_hh :
[[1 1]
 [1 1]
 [1 1]]
w_hh shape : (3, 2) 

w_hx :
[[9 9 9]
 [9 9 9]
 [9 9 9]]
w_hx shape : (3, 3) 

joining
ww_h1 shape (3, 5)
hstack
w_h2 shape (3, 5)


## Hidden and State Inputs

In [9]:
h_t_prev = np.full((2,1), 1)
x_t = np.full((3,1), 9)


print("data")
print(f"h_t_prev {h_t_prev}")
print(f"h_t_prev shape {h_t_prev.shape}")
print(f"x_t {x_t}")
print(f"x_t shape {x_t.shape}")

print("joining arrays")

print("Option 1 - concatenate")
ax_1 = np.concatenate((h_t_prev, x_t), axis=0)

print(f"ax_1 {ax_1}")
print(f"ax_1 shape {ax_1.shape}")

print("Option 2 - vstack")

ax_2 = np.vstack((h_t_prev, x_t))

print(f"ax_2 {ax_2}")
print(f"ax_2 shape {ax_2.shape}")

data
h_t_prev [[1]
 [1]]
h_t_prev shape (2, 1)
x_t [[9]
 [9]
 [9]]
x_t shape (3, 1)
joining arrays
Option 1 - concatenate
ax_1 [[1]
 [1]
 [9]
 [9]
 [9]]
ax_1 shape (5, 1)
Option 2 - vstack
ax_2 [[1]
 [1]
 [9]
 [9]
 [9]]
ax_2 shape (5, 1)


## Verify Formulas
Now you know how to do the concatenations, horizontal and vertical, lets verify if the two formulas produce the same result.

__Formula 1:__ $h^{<t>}=g(W_{h}[h^{<t-1>},x^{<t>}] + b_h)$ 

__Formula 2:__ $h^{<t>}=g(W_{hh}h^{<t-1>} + W_{hx}x^{<t>} + b_h)$


To prove:- __Formula 1__ $\Leftrightarrow$ __Formula 2__

We will ignore the bias term $b_h$ and the activation function $g(\ )$ because the transformation will be identical for each formula. So what we really want to compare is the result of the following parameters inside each formula:

$W_{h}[h^{<t-1>},x^{<t>}] \quad \Leftrightarrow \quad W_{hh}h^{<t-1>} + W_{hx}x^{<t>} $

We'll see how to do this using matrix multiplication combined with the data and techniques (stacking/concatenating) from above.

* Try adding a sigmoid activation function and bias term to the checks for completeness.


In [ ]:
w_hh = np.full((3,2), 1)
w_hx = np.full((3,3), 9)

h_t_prev = np.full((2,1), 1)
x_t = np.full((3,1), 9)

print("Results")
stack_1 = np.hstack((w_hh, w_hx))
stack_2 = np.vstack((h_t_prev, x_t))

print("\nFormula 1")
print("Term1:\n",stack_1)
print("Term2:\n",stack_2)
formula_1 = np.matmul(np.hstack((w_hh, w_hx)), np.vstack((h_t_prev, x_t)))
print("Output:")
print(formula_1)

# Formula 2
mul_1 = np.matmul(w_hh, h_t_prev)
mul_2 = np.matmul(w_hx, x_t)
print("\nFormula 2")
print("Term1:\n",mul_1)
print("Term2:\n",mul_2)

formula_2 = np.matmul(w_hh, h_t_prev) + np.matmul(w_hx, x_t)
print("\nOutput:")
print(formula_2, "\n")

# Verification 
# np.allclose - to check if two arrays are elementwise equal upto certain tolerance, here  
# https://numpy.org/doc/stable/reference/generated/numpy.allclose.html

print("-- Verify --")
print("Results are the same :", np.allclose(formula_1, formula_2))