In [2]:
import numpy as np

### Sum

In [31]:
m1 = np.array([[1,2,3],[2,3,4],[4,5,6]])
m1

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

Sum along axis 0

In [32]:
m = np.sum(m1, axis=0)
m

array([ 7, 10, 13])

Sum along axis 1

In [33]:
m = np.sum(m1, axis=1)
m

array([ 6,  9, 15])

### Equality

In [34]:
m1 = np.array([1,2,3,4])
m2 = np.array([2,2,3,4])

m3 = np.equal(m1, m2)
m3

array([False,  True,  True,  True])

In [35]:
m3 = np.equal(m1, 1)
m3

array([ True, False, False, False])

In [36]:
m4 = (m1 == m3)
m4

array([ True, False, False, False])

### Dot Product

In [37]:
m1 = np.array([1,2,3,4])
m2 = np.array([1,2,3,4])
m3 = np.dot(m1, m2)
m3

30

In [38]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[1,2],[3,4],[5,6]])
m3 = np.dot(m1, m2)
m3

array([[22, 28],
       [49, 64]])

### Transpose

In [39]:
m1 = np.array([[1,2,3]])
m1_t = m1.T
m1_t

array([[1],
       [2],
       [3]])

### Matmul

In [40]:
m1 = [[1,2,3],[3,4,5]]
m2 = []

### Expand Dims

In [41]:
m1 = np.array([1,2])

Expand dims along axis 0

In [42]:
m1_0 = np.expand_dims(m1, axis=0)
m1_0

array([[1, 2]])

Expand dims along axis 1

In [43]:
m1_1 = np.expand_dims(m1, axis=1)
m1_1

array([[1],
       [2]])