In [1]:
import tensorflow as tf
import numpy as np

2024-01-21 12:23:02.893307: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-21 12:23:03.890747: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-21 12:23:03.891102: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-21 12:23:03.969911: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-21 12:23:04.216087: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-21 12:23:04.225964: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [2]:
text = "welcome to the jungle"
text_tensor = tf.convert_to_tensor(text)
text_tensor

<tf.Tensor: shape=(), dtype=string, numpy=b'welcome to the jungle'>

In [3]:
next_token = tf.fill((1,1), -1)
next_token

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[-1]], dtype=int32)>

In [7]:
t1 = [[1,2,3], [4,5,6]]
t2 = [[2,4,5], [6,7,8]]

In [8]:
conc1 = tf.concat([t1, t2], axis=0)
conc1

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [2, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [9]:
conc1 = tf.concat([t1, t2], axis=-1)
conc1

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 2, 3, 2, 4, 5],
       [4, 5, 6, 6, 7, 8]], dtype=int32)>